name: GitHub Profile Summary Cards

on:
  # Runs once a day at midnight (UTC)
  schedule:
    - cron: "0 0 * * *"
  # Lets you run it manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate GitHub Profile Summary Cards
    steps:
      - uses: actions/checkout@v3
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: Xzone2486
